version: '3.9'

services:
    scheduler:
        build: .
        container_name: scheduling-app
        env_file:
            - .env
        volumes:
            - ./data:/data
            - ./credentials:/credentials
        command: >
            python -m app.main
